stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - docker build -t waicolle .

deploy:
  stage: deploy
  script:
    - cd /docker && docker-compose up -d --force-recreate waicolle
  after_script:
    - docker image prune -f
  only:
    - main
