name: CI

on:
  push:
    branches: ["main", "renovate/*"]
    tags: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    if: startsWith(github.ref, 'refs/tags/') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: |
          wget $NANAPI_OPENAPI
          npm run codegen -- openapi.json
        env:
          NANAPI_OPENAPI: ${{ secrets.NANAPI_OPENAPI }}
      - run: npm run typecheck
